# Generated by Django 3.2.2 on 2021-05-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210504_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.offer')),
            ],
        ),
    ]
